[build]
  command = "yarn run build"
  publish = "public"

[dev]
  command = "remix dev"
  port = 3000

[[plugins]]
  package = "@netlify/remix-adapter"

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
